### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by WoLfulus** [TallerWebSolutions/taller-test#19]
Hi!

I'm doing these tests, and I found it a little bit annoying to work with (entering the container and stuff). I ask this as each task is a different pull request and I'm wondering if am I allowed to actually make some structural changes to the repository before opening each PR? 
I found some issues running on Windows that I wanted to make it easier too.

Thanks!

**Comment by lucasconstantino** [comment]
You are welcome to do it! In fact, if you manage to enhance developer experience on Windows, we would love a pull-request here ;)

**Comment by WoLfulus** [comment]
Awesome! Thanks
