### ISSUE TITLE
The Software It's not Registering a new user

### ISSUE THREAD

**Issue by correar** [TallerWebSolutions/taller-test#9]
When I try register a new user, the register button change to "registering" but it doesn't do the action.
At Network devtool tab show faild message when the page try to connect grahql using localhost.

I'm accessing by external IP, ex.: 192.168.1.5:3000

If I try to access http://192.168.1.5/graphql/explorer works fine.
![graphql](https://user-images.githubusercontent.com/10153867/40136871-5c63d3be-591f-11e8-9920-ed4f72b9f35a.png)

**Comment by lucasconstantino** [comment]
@correar is there any error shown in the console? It might be a problem with CORS

**Comment by correar** [comment]
yes, Failed to send WACHDOG=1 notification message: Transport endpoint is not connected
![console_error](https://user-images.githubusercontent.com/10153867/40142445-f9f4ff5e-592e-11e8-8878-637c909c5859.png)

**Comment by lucasconstantino** [comment]
@correar is there any error in the _browser_ console? Besides the network issue presented...

**Comment by correar** [comment]
![console_error_web](https://user-images.githubusercontent.com/10153867/40145581-d5657074-5938-11e8-8a42-b7b4e5b79278.png)

**Comment by correar** [comment]
I've changed initApollo.js.

// const GRAPHQL_HOST = process.env.GRAPHQL_HOST
const GRAPHQL_HOST = 'http://<my_ip>/graphql';

and the failed error it isn't showing anymore, now it's showing I'm already looged in, but It's already a ticket open of this issue. I'll see what I need to do.

**Comment by correar** [comment]
maybe it's better to change procees.env.GRAPHQL_HOST, but until now I did'nt find where is this information.

**Comment by correar** [comment]
I readed the issue of 80 port and there 
it has how how to configure GRAPHQL_HOST.
Just edit Dockerfile and after do it rebuild docker.
